plugins:
  place_town_user_count_min:
    default: 50
    client: true
  place_neighbourhood_user_count_min:
    default: 30
    client: true
  place_town_change_min:
    default: 30
    client: true
  place_neighbourhood_change_min:
    default: 30
    client: true
  place_country_active_min:
    default: 3
    client: true
  place_urban_types:
    type: 'list'
    default: 'city|town|village'
    choices:
      - city
      - town
      - village
      - hamlet
  place_neighbourhood_types:
    type: 'list'
    default: 'town|village|suburb|quarter|neighbourhood'
    choices:
      - town
      - village
      - hamlet
      - borough
      - suburb
      - quarter
      - neighbourhood
